# .github/workflows/builder.yml
---
name: Node.js CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: Build
        run: |
          npm install --force
          npm ci
          npm run build && npm run start && touch out/.nojekyll
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.

